on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Compile and Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["aarch64-unknown-linux-musl", "loongarch64-unknown-linux-musl", "riscv64gc-unknown-linux-musl", "x86_64-unknown-linux-musl", "arm-unknown-linux-musleabi", "arm-unknown-linux-musleabihf", "armv5te-unknown-linux-musleabi", "armv7-unknown-linux-musleabi", "armv7-unknown-linux-musleabihf", "i586-unknown-linux-musl", "i686-unknown-linux-musl"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install toolchain for target ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build for target ${{ matrix.target }}
        run: cargo build --release "--target=${{ matrix.target }}"
      - name: Rename build
        run: mv "target/${{ matrix.target }}/release/waylrc" "target/waylrc-${{ matrix.target }}"
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: target/waylrc-${{ matrix.target }}
